-- ashen edge
-- color 14 = transparent

--##generated##
-- (replaced by build.py)
-- char_base, cell_w, cell_h, trans
-- anim indices, anchor data
--##end##

-- combo chain: z press cycles
-- attack1 -> cross_slice
combo_chain={a_atk1,a_xslice}

-- game state: 0=title, 1=play
gs,tt,zt=1,0,nil

-- fade: v=0 clear, v=8 black, d=direction (1=out,-1=in,0=idle)
fade_v,fade_d,fade_t=8,-1,0
-- screen palette darkening table (colors 1-15, 8 steps toward black)
-- flat: row c = indices (c-1)*8+1..(c-1)*8+8, access via fdp[(c-1)*8+v]
fdp=split"1,1,1,1,0,0,0,0,2,2,2,1,1,0,0,0,3,3,4,5,2,1,1,0,4,4,2,2,1,1,1,0,5,5,2,2,1,1,1,0,6,6,13,5,2,1,1,0,7,7,6,13,5,2,1,0,8,8,9,4,5,2,1,0,9,9,4,5,2,1,1,0,10,15,9,4,5,2,1,0,11,11,3,4,5,2,1,0,12,12,13,5,5,2,1,0,13,13,5,5,2,1,1,0,14,9,9,4,5,2,1,0,15,14,9,4,5,2,1,0"
function apply_fade(v)
 if v==0 then
  for c=0,15 do pal(c,c,1) end
  return
 end
 for c=1,15 do pal(c,fdp[(c-1)*8+v],1) end
 pal(0,0,1)
end

-- aspd generated by build.py (unified anim speed table)

-- physics

-- spider surface-crawling tables
-- indexed by surf+1: 1=floor,2=rwall,3=ceil,4=lwall
sf_dx=split"1,0,-1,0"  -- canonical forward dx
sf_dy=split"0,-1,0,1"  -- canonical forward dy
sd_dx=split"0,1,0,-1"  -- surface "down" dx
sd_dy=split"1,0,-1,0"  -- surface "down" dy
sp_rot=split"0,3,2,1"  -- draw rotation per surface
snpx=split"8,16,8,-1"  -- snap probe x offset per surface
snpy=split"16,8,-1,8"  -- snap probe y offset per surface

-- collision box: x from px-3 to px+3, y from py+3 to py+19

-- player state
px,py,vx,vy=64,0,0,0
facing,grounded,prev_by1,air_time=1,true,0,0

-- animation state
state="idle"
cur_anim,cur_frame,anim_timer=a_idle,1,0

-- combo state
combo_idx,combo_queued=0,false

-- input buffer (frames remaining)
buf_jump,buf_atk,buf_sweep=0,0,0

-- attack movement tracking
atk_anchor0,atk_px0,air_atk=0,0,false

-- forward push on attack end
-- order: idle,run,jump,fall,hit,land,atk1,xslice,sweep,death
atk_push=split"0,0,0,0,0,0,4,6,0,0"

-- particles & collectibles
parts={}
gems=0   -- collected count

-- player HP
plr_hp,plr_inv,death_t,ckpt_x,ckpt_y,safe_x,safe_y=3,0,0,0,0,0,0
ptl_rm={[5]=2,[6]=8,[7]=8}

-- spider projectiles
sprojs={}

-- entity system
ents={}
ent_grp={}

-- -- decoders --

function pk2(a)
 return peek(a)+peek(a+1)*256
end

function decode_eg2(off,npix,bpp,w)
 local by=peek(off) off+=1
 local bi=0
 local function rb()
  local v=(by>>bi)&1 bi+=1
  if bi>7 then by=peek(off) off+=1 bi=0 end
  return v
 end
 local mode=rb()+rb()*2+rb()*4
 local k=rb()+rb()*2+1
 local ks=1<<k
 local function eg()
  local z=0
  while rb()==0 do z+=1 end
  local v=1
  for i=1,z+k do v=v*2+rb() end
  return v-ks
 end
 local buf={}
 local pb,pv,pi=0,0,1
 while pi<=npix do
  local z=eg()
  while true do
   for i=1,z do
    pv=pv*2 pb+=1
    if pb==bpp then buf[pi],pv,pb=pv,0,0 pi+=1 end
   end
   if z<16383 then break end
   z=eg()
  end
  if pi<=npix then
   pv=pv*2+1 pb+=1
   if pb==bpp then buf[pi],pv,pb=pv,0,0 pi+=1 end
  end
 end
 if mode==1 then
  for i=2,npix do
   if (i-1)%w>0 then buf[i]=buf[i]^^buf[i-1] end
  end
 elseif mode==2 then
  for i=w+1,npix do buf[i]=buf[i]^^buf[i-w] end
 elseif mode==3 then
  for i=w+2,npix do
   if (i-1)%w>0 then buf[i]=buf[i]^^buf[i-w-1] end
  end
 elseif mode==4 then
  for i=2,npix do
   local x=(i-1)%w
   local a,b,c=x>0 and buf[i-1] or 0,i>w and buf[i-w] or 0,x>0 and i>w and buf[i-w-1] or 0
   local p,r=a+b-c
   local pa,pc=abs(p-a),abs(p-c)
   r=pa<=abs(p-b) and pa<=pc and a or abs(p-b)<=pc and b or c
   buf[i]=buf[i]^^r
  end
 end
 return buf
end

function read_anim(a,cb)
 cb=cb or char_base
 local na=peek(cb)
 local ab=cb+3+na*2+pk2(cb+3+(a-1)*2)
 local nf=peek(ab)
 local atype=peek(ab+1)
 local bpp=peek(ab+2)
 local np=bpp<4 and (1<<bpp) or 0
 local pal={}
 for i=0,np-1 do
  local b=peek(ab+3+i\2)
  pal[i+1]=i%2==0 and (b>>4)&0xf or b&0xf
 end
 local h=ab+3+np\2
 if atype==5 then
  return {nf=nf,bpp=bpp,pal=pal,atype=5,fo_off=h,data_off=h+nf*2}
 end
 local bx,by,bw,bh=peek(h,4)
 local ro=h+4
 return {
  nf=nf,bpp=bpp,pal=pal,atype=atype,
  bx=bx,by=by,bw=bw,bh=bh,
  ref_off=ro,fo_off=ro+nf,
  data_off=ro+nf*3
 }
end

acache={}
sp_anc={}

function decode_anim(ai)
 local frames={}
 local hp=ai.bpp<4
 if ai.atype==5 then
  for f=1,ai.nf do
   local foff=pk2(ai.fo_off+(f-1)*2)
   local fa=ai.data_off+foff
   local bx,by,bw,bh=peek(fa,4)
   if bw==0 then
    frames[f]={"",0,0,0,0}
   else
    frames[f]={decode_eg2(fa+4,bw*bh,ai.bpp,bw),bx,by,bw,bh}
   end
  end
 else
  local npix=ai.bw*ai.bh
  for f=1,ai.nf do
   local ref=peek(ai.ref_off+f-1)
   local foff=pk2(ai.fo_off+(f-1)*2)
   local fa=ai.data_off+foff
   if ref==254 then
    local bx,by,bw,bh=peek(fa,4)
    if bw==0 then
     frames[f]={"",0,0,0,0}
    else
     frames[f]={decode_eg2(fa+4,bw*bh,ai.bpp,bw),bx,by,bw,bh}
    end
   else
    local d=decode_eg2(fa,npix,ai.bpp,ai.bw)
    if ref~=255 then
     local base=frames[ref+1][1]
     for i=1,npix do d[i]=d[i]^^base[i] end
    end
    frames[f]={d,ai.bx,ai.by,ai.bw,ai.bh}
   end
  end
 end
 for f=1,#frames do
  local d=frames[f][1]
  if type(d)~="string" then
   if hp then for i=1,#d do d[i]=ai.pal[d[i]+1] or trans end end
   frames[f][1]=chr(unpack(d))
  end
 end
 return frames
end

function la(b,a0,cw,ch)
 for a=1,peek(b) do
  local ai=read_anim(a,b)
  acache[a0+a-1]={ai=ai,frames=decode_anim(ai),cw=cw,ch=ch}
 end
end

function cache_anims()
 la(char_base,1,cell_w,cell_h)
 la(title_base,a_title,128,128)
 la(font_base,a_font,font_cw,font_ch)
 la(spider_base,a_spi,spider_cw,spider_ch)
 la(wheelbot_base,a_wbi,wheelbot_cw,wheelbot_ch)
 la(hellbot_base,a_hbi,hellbot_cw,hellbot_ch)
 la(portal_base,a_ptl,portal_cw,portal_ch)
 la(torch_base,a_torch,torch_cw,torch_ch)
 la(box_base,a_box,box_s,box_s)
 local ai=read_anim(1,hp_base)
 hp_buf=decode_anim(ai)[1][1]
end

function hurt_plr()
 if plr_inv==0 and state~="death" then
  plr_hp-=1
  plr_inv=60
  px,py=safe_x,safe_y
  vx,vy=0,0
  set_anim(a_hit,"land")
  if plr_hp<=0 then
   set_anim(a_death,"death")
   death_t=0
  end
 end
end

function draw_hp()
 local fill=hp_w*(1-plr_hp/3)
 local tt=time()*3
 local idx=1
 for y=0,hp_h-1 do
  local wave=sin(y*0.12+tt)*1.5
  for x=0,hp_w-1 do
   local c=ord(hp_buf,idx)
   if c==0 then
    pset(x,y,0)
   elseif c==7 then
    if hp_w-1-x>=fill+wave then
     pset(x,y,8)
    else
     pset(x,y,7)
    end
   end
   idx+=1
  end
 end
end

function draw_char(a,f,sx,sy,flip,rot,rm)
 local buf,bx,by,bw,bh=unpack(acache[a].frames[f])
 if bw==0 then return end
 local cw=acache[a].cw
 local idx=1
 for y=0,bh-1 do
  for x=0,bw-1 do
   local col=ord(buf,idx)
   if rm then col=rm[col] or col end
   if col~=trans then
    local dx,dy=flip and cw-1-bx-x or bx+x,by+y
    if rot==1 then
     dx,dy=cw-1-dy,dx
    elseif rot==2 then
     dx,dy=cw-1-dx,cw-1-dy
    elseif rot==3 then
     dx,dy=dy,cw-1-dx
    end
    pset(sx+dx,sy+dy,col)
   end
   idx+=1
  end
 end
end

-- -- animation helpers --

function set_anim(a,s)
 if cur_anim~=a then
  cur_anim,cur_frame,anim_timer=a,1,0
 end
 if s then state=s end
end

function anim_done(m)
 local nf=acache[cur_anim].ai.nf
 return cur_frame>=nf
  and anim_timer>=aspd[cur_anim]-1-(m or 0)
end

function tick_anim()
 anim_timer+=1
 if anim_timer>=aspd[cur_anim] then
  anim_timer=0
  if cur_frame<acache[cur_anim].ai.nf then
   cur_frame+=1
  elseif state=="idle" or state=="run" then
   cur_frame=1
  end
 end
end

-- -- tile/map system --

-- map buffers: mdat[layer][y*lvl_w+x+1]
-- layer 1=bg, 2=main, 3=fg
mdat={}
cam_x,cam_y=0,0

function load_tiles()
 local sz=lvl_w*lvl_h
 if lvl_nt==0 then
  for L=1,lvl_nl do
   mdat[L]={}
   for i=1,sz do mdat[L][i]=0 end
  end
  return
 end
 local nt,nl=peek(map_base,2)
 local p=map_base+12+nl*2
 local tbpp=peek(p)
 local tnp=1<<tbpp
 local tpal={}
 for i=0,tnp-1 do
  local tb=peek(p+1+i\2)
  local c=i%2==0 and(tb>>4)&0xf or tb&0xf
  tpal[i]=c
 end
 local sp=p+1+tnp\2 local ss=pk2(sp) sp+=2
 local function wt(off,n,pal,bg)
  local b=decode_eg2(off,n*256,tbpp,16) local ai=1
  for t=0,n-1 do for py=0,15 do
   local d=bg and 0x8000+t*128+py*8 or(t\8*16+py)*64+t%8*8
   for px=0,7 do
    poke(d+px,(pal[b[ai]]&0xf)|(pal[b[ai+1]]&0xf)<<4) ai+=2
   end
  end end
 end
 wt(sp,lvl_nst,tpal) wt(sp+ss,nt-lvl_nst,tpal,1)
 p+=pk2(map_base+10)
 for L=1,nl do
  local lsz=pk2(map_base+10+L*2)
  local lbpp=peek(p)
  mdat[L]=decode_eg2(p+1,sz,lbpp,lvl_w)
  p+=lsz
 end
 local ne=peek(p) p+=1
 for i=1,ne do
  local a,b,c,d=peek(p,4)
  local e={type=a,tx=b,ty=c,group=d}
  p+=4
  if a==2 or a==6 then
   e.cost=peek(p) p+=1
  elseif a==8 then
   e.tw=peek(p) e.th=peek(p+1) p+=2
  end
  add(ents,e)
  ent_grp[d]=ent_grp[d] or {}
  add(ent_grp[d],#ents)
 end
end

function thi(v) return (v-1)\16 end

function tile_flag(tx,ty)
 if tx<0 or tx>=lvl_w or ty<0 or ty>=lvl_h then return 0 end
 local t=mdat[2][ty*lvl_w+tx+1]\4
 if t==0 then return 0 end
 return tflg[t] or 0
end

function tile_solid(tx,ty)
 return tile_flag(tx,ty)&9>0 or ent_solid(tx,ty)
end

function box_hits_solid(bx0,by0,bx1,by1)
 local tx0,ty0,tx1,ty1=bx0\16,by0\16,thi(bx1),thi(by1)
 for ty=ty0,ty1 do
  for tx=tx0,tx1 do
   if tile_solid(tx,ty) then
    return true
   end
  end
 end
end

function land_on(y_top)
 py,vy=y_top-19,0
 if not grounded then
  grounded=true
  air_time=0
  if state=="fall" then
   set_anim(a_land,"land")
  end
 end
end

function resolve_y()
 local bx0,by0,bx1,by1=px-3,py+3,px+3,py+19
 if box_hits_solid(bx0,by0,bx1,by1) then
  if vy>=0 then
   land_on(thi(by1)*16)
  elseif vy<0 then
   py,vy=(by0\16+1)*16-3,0
  end
  return
 end
 if vy>=0 then
  local tx0,tx1,ty=bx0\16,thi(bx1),by1\16
  local ptop=ty*16
  if prev_by1<=ptop then
   for tx=tx0,tx1 do
    if tile_flag(tx,ty)&2>0 then
     land_on(ptop)
     return
    end
   end
  end
 end
 grounded=false
end

function tr(cx,cy)
 local x,y=max(0,cx\16),max(0,cy\16)
 return x,y,min(lvl_w-1,x+8),min(lvl_h-1,y+8)
end

function draw_mem_layer(L)
 local md=mdat[L]
 if not md then return end
 local p=lplx[L]
 local cx,cy=flr(pax+dcx*p)\2*2,flr(pay+dcy*p)
 local tx0,ty0,tx1,ty1=tr(cx,cy)
 for ty=ty0,ty1 do
  for tx=tx0,tx1 do
   local c=md[ty*lvl_w+tx+1]
   if c>0 then
    local src=0x8000+(c-lvl_nst-1)*128
    for py=0,15 do memcpy(0x1c38+py*64,src+py*8,8) end
    spr(238,tx*16-cx,ty*16-cy,2,2)
   end
  end
 end
end

function tspr(c,x,y)
 local t=c\4
 spr((t-1)\8*32+(t-1)%8*2,x,y,2,2,c&2>0,c&1>0)
end

function draw_main_layer()
 local md=mdat[2]
 if not md then return end
 local p=lplx[2]
 local cx,cy=pax+dcx*p,pay+dcy*p
 local tx0,ty0,tx1,ty1=tr(cx,cy)
 for ty=ty0,ty1 do
  for tx=tx0,tx1 do
   local c=md[ty*lvl_w+tx+1]
   if c>0 then tspr(c,tx*16-cx,ty*16-cy) end
  end
 end
end

function update_camera()
 local target_x,target_y=mid(0,px-64,lvl_w*16-128),mid(0,py-64,lvl_h*16-128)
 -- smooth follow, round to whole pixels
 cam_x+=flr((target_x-cam_x)*0.15+0.5)
 cam_y+=flr((target_y-cam_y)*0.15+0.5)
 dcx,dcy=cam_x-pax,cam_y-pay
end

-- -- game --

function reset_game()
 plr_hp,plr_inv=3,0
 px,py=ckpt_x,ckpt_y
 safe_x,safe_y=px,py
 vx,vy=0,0
 set_anim(a_idle,"idle")
 grounded,death_t=true,0
 gems,sprojs=0,{}
 ents,ent_grp={},{}
 load_tiles()
 init_ents()
end

function _init()
 palt(0,false)
 palt(trans,true)
 cache_anims()
 -- load tiles into sprite sheet (overwrites __gfx__)
 -- entity tiles in __gfx__ survive since they're after map tiles
 load_tiles()
 init_ents()
 -- set player to spawn
 px,py=spn_x*16+8,spn_y*16
 pax,pay=px-64,py-64
 ckpt_x,ckpt_y=px,py
 safe_x,safe_y=px,py
 music(0)
end

function do_jump()
 vy,grounded=-3.5,false
 set_anim(a_jump,"jump")
 buf_jump=0
end

function sa(a)
 atk_anchor0,atk_px0=anc[a][1],px
end

function start_combo()
 combo_idx=1
 combo_queued=false
 vx=0
 set_anim(combo_chain[1],"attack")
 sa(combo_chain[1])
 buf_atk=0
end

function start_sweep()
 vx=0
 set_anim(a_sweep,"sweep")
 sa(a_sweep)
 air_atk=false
 buf_sweep=0
end

function start_air_atk()
 air_atk=true
 cur_anim,cur_frame,anim_timer=a_xslice,1,0
 sa(a_xslice)
 state="sweep"
 buf_atk,buf_sweep=0,0
end

function try_move_x(dx)
 -- move px by dx, stepping to avoid
 -- skipping through thin walls
 local rem,dir=abs(dx),sgn(dx)
 while rem>0 do
  local d=min(rem,6)
  px+=d*dir
  rem-=d
  local bx0,by0,bx1,by1=px-3,py+3,px+3,py+19
  if box_hits_solid(bx0,by0,bx1,by1) then
   if dir>0 then
    px=thi(bx1)*16-3
   else
    local tx0=bx0\16
    px=(tx0+1)*16+3
   end
   return
  end
 end
end

function apply_atk_drift()
 -- move px each frame to follow anchor
 -- drift, with wall collision
 local ax=anc[cur_anim][cur_frame]
 local drift=ax-atk_anchor0
 local target=atk_px0+drift*facing
 local dx=target-px
 if dx~=0 then try_move_x(dx) end
end

function end_attack()
 local push=atk_push[cur_anim] or 0
 if push~=0 then
  try_move_x(push*facing)
 end
end

function damp() vx*=0.8 if abs(vx)<0.1 then vx=0 end end

function air_control(lr)
 if lr~=0 then
  vx=lr*1.5
  facing=lr
 else
  damp()
 end
end

function check_attacks()
 local ax0=facing>0 and px+3 or px-17
 local ax1=ax0+14
 local ay0,ay1=py+3,py+19
 local function h(x,y,m) return ax1>x-m and ax0<x+m+16 and ay1>y-m and ay0<y+m+16 end
 local tx0,ty0,tx1,ty1=ax0\16,ay0\16,thi(ax1),thi(ay1)
 for ty=ty0,ty1 do
  for tx=tx0,tx1 do
   local fl=tile_flag(tx,ty)
   if fl&12>0 then
    local k=ty*lvl_w+tx+1
    local c=mdat[2][k] mdat[2][k]=0
    if fl&8>0 then mkp(tx*16,ty*16,3).c=c
    else for i=1,3 do mkp(tx*16+8,ty*16+8,3) end end
   end
  end
 end
 for e in all(ents) do
  local t=e.type
  if t==7 then
   if h(e.x,e.y,8) then e.lit,e.frame=false,7
    local p=mkp(e.x+8,e.y+8,1) p.cl=8 p.vx=rnd(1)-.5 p.vy=rnd(1)-.5 end
  elseif t==3 and e.hp>0
   and e.state~="death" and e.inv_t==0 then
   if h(e.x,e.y,0) then
    ent_hurt(e,a_spd,a_sph)
   end
  elseif t\2==2 and e.hp>0
   and e.state~="death" and e.state~="sleep"
   and (t~=4 or e.state~="fdash") and e.inv_t==0 then
   local wb=t==4
   local hw=wb and 14 or 15
   if ax1>e.x-hw and ax0<e.x+hw
    and ay1>e.y-(wb and 24 or 28) and ay0<e.y then
    ent_hurt(e,wb and a_wbdt or a_hbd,wb and a_wbd or a_hbh)
   end
  end
 end
end
function mkp(x,y,s)
 local p={x=x,y=y,vx=rnd(s)-s/2,vy=-rnd(s)-1,age=0}
 add(parts,p) return p
end
function update_parts()
 for p in all(parts) do
  p.x+=p.vx p.y+=p.vy
  if not p.cl then
   if tile_flag(p.x\16,p.y\16)&9>0 then
    p.y-=p.vy p.vy*=-0.4 p.vx*=0.7
   end
   p.vy+=0.08
  end
  p.age+=1
  if p.c or p.cl then
   if p.age>30 then del(parts,p) end
  elseif p.age>15 and abs(p.x-px)<10 and abs(p.y-py-11)<10 then
   gems+=1 del(parts,p)
  elseif p.age>900 then del(parts,p)
  end
 end
end

-- -- entity system --

function init_bot(e,a,hp)
 e.x,e.y=e.tx*16+8,(e.ty+1)*16
 e.vx,e.vy,e.mdir=0,0,1
 e.anim,e.frame=a,1
 e.state,e.anim_t="sleep",0
 e.hp,e.inv_t,e.atk_cd=hp,0,0
 e.grounded,e.fired=false,false
 e.patrol_t,e.walk_count=0,0
end

function init_ents()
 for e in all(ents) do
  local t=e.type
  if t==1 then
   e.anim,e.frame,e.state=a_door,15,0
  elseif t==2 then
   e.x,e.y,e.anim,e.frame=e.tx*16+8,e.ty*16+8,a_sid,1
   e.state,e.cooldown,e.cost=0,0,e.cost or 0
  elseif t==3 then
   e.x,e.y=e.tx*16,e.ty*16
   e.surf,e.mdir=0,1
   e.anim,e.frame=a_spi,1
   e.state="idle"
   e.anim_t,e.hp=0,3
   e.atk_cd,e.fired=0,false
   e.inv_t,e.move_acc=0,0
   e.patrol_t,e.walk_count=60,0
  elseif t==4 then init_bot(e,a_wbi,4)
  elseif t==5 then init_bot(e,a_hbi,5)
  elseif t>=6 then
   e.x,e.y=e.tx*16,e.ty*16
   if t==6 then
    e.x+=8 e.y+=16
    e.anim,e.frame=a_ptl,1
    e.anim_t,e.active,e.cost=0,false,e.cost or 0
   elseif t==7 then
    e.anim,e.frame=a_torch,1
    e.anim_t,e.lit=0,true
   end
  end
 end
end

function ent_solid(tx,ty)
 for e in all(ents) do
  if e.type==1
   and (e.state==0 or e.state==3)
  then
   if tx==e.tx
    and ty>=e.ty and ty<e.ty+3 then
    return true
   end
  end
 end
end

function toggle_switch(e)
 if e.cooldown>0 then return end
 e.cooldown=30
 if e.state==0 then
  -- off -> activating (press down)
  e.state,e.anim,e.frame=1,a_sdn,1
 elseif e.state==2 then
  -- on -> deactivating (pop back up)
  e.state,e.anim,e.frame=3,a_sst,1
 end
 -- trigger linked doors
 local grp=ent_grp[e.group]
 if grp then
  for _,ei in ipairs(grp) do
   local de=ents[ei]
   if de.type==1 then
    if e.state==1 then
     de.state,de.frame=1,1
    elseif e.state==3 then
     de.state,de.frame=3,14
    end
   end
  end
 end
end

function ent_hurt(e,da,ha)
 e.hp,e.inv_t=e.hp-1,20
 if e.hp<=0 then
  e.vx=0 sp_set_anim(e,da,"death")
 else
  e.vx=0 sp_set_anim(e,ha,"hit")
 end
end

function fire_at(sx,sy,spd)
 local dx,dy=px-sx,py+11-sy
 local d=max(abs(dx),abs(dy))
 if d>0 then
  add(sprojs,{x=sx,y=sy,dx=dx/d*spd,dy=dy/d*spd,exp=false,et=0})
 end
end

function sp_set_anim(e,a,s)
 if e.anim~=a then
  e.anim,e.frame,e.anim_t=a,1,0
 end
 if s then e.state=s end
end

function ff(e) if e.frame==3 and not e.fired then e.fired=true return true end end

function go_idle(e,a,pt)
 sp_set_anim(e,a,"idle")
 e.patrol_t=pt
end

function patrol_start(e,a)
 e.walk_count+=1
 if e.walk_count%2==0 then e.mdir=-e.mdir end
 e.patrol_t=120
 sp_set_anim(e,a)
end

-- probe: check two tile_solid points
-- along an edge in direction dx,dy
function sp_probe(x,y,dx,dy)
 if dx~=0 then
  local tx=(dx>0 and x+16 or x-1)\16
  return tile_solid(tx,(y+2)\16)
   or tile_solid(tx,(y+13)\16)
 else
  local ty=(dy>0 and y+16 or y-1)\16
  return tile_solid((x+2)\16,ty)
   or tile_solid((x+13)\16,ty)
 end
end

-- snap spider feet to nearest
-- solid tile on current surface
function sp_snap(e)
 local s=e.surf+1
 local dx,dy=sd_dx[s],sd_dy[s]
 local tx,ty=(e.x+snpx[s])\16,(e.y+snpy[s])\16
 if tile_solid(tx,ty) then
  if dx~=0 then e.x=(tx-sgn(dx))*16
  else e.y=(ty-sgn(dy))*16 end
 end
end

-- move spider 1px along surface
function step_spider(e)
 local s=e.surf+1
 local fdx,fdy=sf_dx[s]*e.mdir,sf_dy[s]*e.mdir
 local nx,ny=e.x+fdx,e.y+fdy

 if sp_probe(nx,ny,fdx,fdy) then
  -- inner corner: wall ahead
  e.surf=(e.surf+e.mdir)%4
  sp_snap(e)
 elseif not sp_probe(nx,ny,sd_dx[s],sd_dy[s]) then
  -- outer corner: no ground ahead
  -- shift position into the surface
  e.x+=sd_dx[s]*16
  e.y+=sd_dy[s]*16
  e.surf=(e.surf-e.mdir+4)%4
  sp_snap(e)
 else
  -- straight movement
  e.x,e.y=nx,ny
 end
end

function wb_move(e)
 if not e.grounded then
  e.vy=min(e.vy+0.15,3)
 end
 e.x+=e.vx
 if box_hits_solid(e.x-14,e.y-24,e.x+14,e.y) then
  if e.vx>0 then e.x=(e.x+13.99)\16*16-14
  elseif e.vx<0 then e.x=(e.x-14)\16*16+30 end
  e.vx=0
 end
 e.y+=e.vy
 if box_hits_solid(e.x-14,e.y-24,e.x+14,e.y) then
  if e.vy>=0 then
   e.y,e.vy,e.grounded=thi(e.y)*16,0,true
  else
   e.y,e.vy=(e.y-24)\16*16+16+24,0
  end
 else e.grounded=false end
end

function ent_tick(e,spd)
 e.anim_t=(e.anim_t or 0)+1
 if e.anim_t>=spd then
  e.anim_t=0
  return true,acache[e.anim].ai.nf
 end
end

function af(e,nf)
 if e.frame<nf then e.frame+=1 return end
 return true
end

function tc(e)
 if e.inv_t>0 then e.inv_t-=1 end
 if e.atk_cd>0 then e.atk_cd-=1 end
end

function update_spider(e)
 local spd=aspd[e.anim] or 6
 local st=e.state
 if st=="death" then
  local tick,nf=ent_tick(e,spd)
  if tick then af(e,nf) end
  return
 end

 tc(e)

 local tick,nf=ent_tick(e,spd)
 if tick then
  if st=="hit" then
   if af(e,nf) then go_idle(e,a_spi,60) end
  elseif st=="attack" then
   if ff(e) then fire_at(e.x+8,e.y+8,2) end
   if af(e,nf) then
    e.atk_cd,e.fired=180,false
    go_idle(e,a_spi,60)
   end
  elseif st=="walk" then
   e.frame=e.frame%nf+1
  end
 end

 if (st=="idle" or st=="walk") and e.atk_cd==0 then
  local ddx,ddy=px-e.x,py-e.y
  if abs(ddx)<80 and abs(ddy)<48 then
   -- face player along surface
   local s=e.surf+1
   local fdx=sf_dx[s]
   local fdy=sf_dy[s]
   local dot=ddx*fdx+ddy*fdy
   e.mdir=dot>=0 and 1 or -1
   sp_set_anim(e,a_spa,"attack")
   return
  end
 end

 -- patrol: idle <-> walk
 if st=="walk" then
  e.move_acc+=0.5
  while e.move_acc>=1 do
   e.move_acc-=1
   step_spider(e)
  end
 end
 e.patrol_t-=1
 if st=="idle" then
  if e.patrol_t<=0 then
   e.state="walk" patrol_start(e,a_spw)
  end
 elseif st=="walk" then
  if e.patrol_t<=0 then
   go_idle(e,a_spi,60)
  end
 end
end

function update_bot(e)
 local wb=e.type==4
 local abi=wb and a_wbi or a_hbi
 local spd=aspd[e.anim] or 6
 local s=e.state
 if s=="death" then
  local t,nf=ent_tick(e,spd)
  if t then af(e,nf) end
  wb_move(e) return
 end
 tc(e)
 local t,nf=ent_tick(e,spd)
 local ddx,ddy=px-e.x,(py+11)-e.y local dist=abs(ddx)
 local function spot()
  if e.atk_cd==0 and dist<(wb and 80 or 90) and abs(ddy)<32 then
   e.vx,e.mdir=0,ddx>0 and 1 or -1
   if wb then
    sp_set_anim(e,a_wbc,"charge")
   elseif dist<32 then
    sp_set_anim(e,a_hba,"attack")
   elseif dist>56 then
    sp_set_anim(e,a_hbs,"shoot")
    e.fired=false
   else
    sp_set_anim(e,a_hbr,"charge")
   end
   return true
  end
 end
 if s=="sleep" then
  if dist<(wb and 64 or 72) and abs(ddy)<48 then
   if wb then
    sp_set_anim(e,a_wbwk,"wake")
   else
    sp_set_anim(e,abi,"idle")
   end
  end
 elseif s=="wake" then
  if t and af(e,nf) then go_idle(e,abi,30) end
 elseif s=="idle" then
  if not spot() then
   e.patrol_t-=1
   if e.patrol_t<=0 then
    e.state=wb and "move" or "run"
    patrol_start(e,wb and a_wbm or a_hbr)
   end
  end
 elseif s=="move" or s=="run" then
  e.vx=e.mdir*(wb and 0.6 or 0.8)
  if t then e.frame=e.frame%nf+1 end
  if not spot() then
   e.patrol_t-=1
   if e.patrol_t<=0 then
    e.vx=0 go_idle(e,abi,60)
   end
  end
 elseif s=="charge" then
  if wb then
   if t and af(e,nf) then
    if dist>48 then
     sp_set_anim(e,a_wbs,"shoot")
     e.fired=false
    else
     sp_set_anim(e,a_wbfd,"fdash")
     e.inv_t=30
    end
   end
  else
   e.vx=e.mdir*1.5
   if t then e.frame=e.frame%nf+1 end
   if dist<32 then
    e.vx=0 sp_set_anim(e,a_hba,"attack")
   end
  end
 elseif s=="shoot" then
  if t then
   if ff(e) then fire_at(e.x,e.y-(wb and 12 or 14),wb and 2.5 or 2) end
   if af(e,nf) then
    e.fired,e.atk_cd=false,wb and 120 or 90
    go_idle(e,abi,wb and 60 or 30)
   end
  end
 elseif s=="fdash" then
  e.vx=e.mdir*3
  if abs(px-e.x)<18 and abs(py+11-e.y+12)<16 then
   hurt_plr()
  end
  if t and af(e,nf) then
   e.vx,e.atk_cd=0,120 go_idle(e,abi,60)
  end
 elseif s=="attack" then
  if t then
   if ff(e) and dist<28 and abs(ddy)<24 then hurt_plr() end
   if af(e,nf) then
    e.fired,e.atk_cd=false,60
    go_idle(e,abi,30)
   end
  end
 elseif s=="hit" then
  if t and af(e,nf) then go_idle(e,abi,60) end
 end
 wb_move(e)
end

function update_sprojs()
 for p in all(sprojs) do
  if p.exp then
   p.et+=1
   if p.et>12 then del(sprojs,p) end
  else
   p.x+=p.dx
   p.y+=p.dy
   p.dy+=0.2
   -- wall collision
   if box_hits_solid(p.x-2,p.y-2,p.x+2,p.y+2) then
    p.exp,p.et=true,0
   -- player collision
   elseif p.x>px-3 and p.x<px+3
    and p.y>py+3 and p.y<py+19 then
    p.exp,p.et=true,0
    hurt_plr()
   -- off screen
   elseif p.x<cam_x-8 or p.x>cam_x+136
    or p.y<cam_y-8 or p.y>cam_y+136 then
    del(sprojs,p)
   end
  end
 end
end

function update_ents()
 zt,near_ent=nil
 for e in all(ents) do
  local t=e.type
  if t==2 then
   if e.cooldown>0 then e.cooldown-=1 end
   if e.state==1 then
    local tick,nf=ent_tick(e,aspd[a_sdn])
    if tick and af(e,nf) then e.state,e.frame=2,nf end
   elseif e.state==3 then
    local tick,nf=ent_tick(e,aspd[a_sst])
    if tick and af(e,nf) then e.state,e.anim,e.frame=0,a_sid,1 end
   end
  elseif t==1 then
   if e.state%2==1 and ent_tick(e,aspd[a_door]) then
    if e.state==1 then
     if e.frame<14 then e.frame+=1
     else e.state,e.frame=2,14 end
    else
     if e.frame>1 then e.frame-=1
     else e.state,e.frame=0,15 end
    end
   end
  elseif t==3 then
   update_spider(e)
  elseif t==6 or t==7 and e.lit then
   local tk,nf=ent_tick(e,6)
   if tk then e.frame=e.frame%(t==7 and 6 or nf)+1 end
   if t==7 and e.lit and abs(px-e.x-8)<11 and abs(py+11-e.y-8)<14 then
    hurt_plr()
   end
  elseif t==8 and px\16>=e.tx and px\16<e.tx+e.tw and py\16>=e.ty and py\16<e.ty+e.th then
   zt=e.group
  elseif t<=5 then
   update_bot(e)
  end
  if (t==2 and e.state==0 or t==6 and not e.active) and abs(px-e.x)<12 and abs(py+8-e.y)<16 then
   near_ent=e
  end
 end
 if near_ent and btnp(3) and gems>=near_ent.cost then
  gems-=near_ent.cost
  if near_ent.type==2 then toggle_switch(near_ent)
  else near_ent.active,ckpt_x,ckpt_y,plr_hp=true,near_ent.x,near_ent.y,3 end
 end
end

function p8print(s,x,y,col)
 local cx,ff=x,acache[a_font].frames
 for i=1,#s do
  local f=font_map[ord(sub(s,i,i))]
  if f and col then
   local buf,bx,by,bw,bh=unpack(ff[f])
   if bw>0 then
    bx+=cx by+=y
    local idx=1
    for dy=0,bh-1 do
     for dx=0,bw-1 do
      if ord(buf,idx)~=trans then
       pset(bx+dx,by+dy,col)
      end
      idx+=1
     end
    end
   end
  end
  cx+=(f and font_adv[f] or font_cw)
 end
 return cx-x
end

function text_box(txt,cx,cy,col)
 local lines=split(txt,"\n",false)
 local nl,mw=#lines,0
 local lw={}
 for i,l in ipairs(lines) do
  lw[i]=p8print(l,0,0)
  if lw[i]>mw then mw=lw[i] end
 end
 local px,py,lh=8,5,font_ch-2
 local bh=lh*nl+py*2
 local bx,by=cx-mw\2-px,cy-bh\2
 local bw=mw+px*2
 local s=box_s
 rectfill(bx+4,by+4,bx+bw-5,by+bh-5,0)
 draw_char(a_box,1,bx,by)
 draw_char(a_box,1,bx+bw-s,by,true)
 draw_char(a_box,1,bx,by+bh-s,true,2)
 draw_char(a_box,1,bx+bw-s,by+bh-s,false,2)
 line(bx+s,by+3,bx+bw-s-1,by+3,7)
 line(bx+s,by+bh-4,bx+bw-s-1,by+bh-4,7)
 line(bx+3,by+s,bx+3,by+bh-s-1,7)
 line(bx+bw-4,by+s,bx+bw-4,by+bh-s-1,7)
 local ty=by+py
 for i,l in ipairs(lines) do
  p8print(l,cx-lw[i]\2,ty,col)
  ty+=lh
 end
end

function draw_bot(e,at,cw,ch)
 if not(e.inv_t>0 and e.inv_t%4<2) then
  local a,f=e.anim,e.frame
  local ax=(at[a] and at[a][f]) or cw\2
  local flip=e.mdir==-1
  local dx=flip and e.x-(cw-1-ax) or e.x-ax
  draw_char(a,f,dx-cam_x,e.y-ch-cam_y,flip)
 end
end

function draw_ents()
 for e in all(ents) do
  local t=e.type
  if t==4 then
   draw_bot(e,wb_anc,wheelbot_cw,wheelbot_ch)
  elseif t==5 then
   draw_bot(e,hb_anc,hellbot_cw,hellbot_ch)
  elseif t==3 then
   local sx,sy=e.x-cam_x,e.y-cam_y
   local flip=e.mdir==-1
   local rot=sp_rot[e.surf+1]
   draw_char(e.anim,e.frame,sx,sy,flip,rot)
  elseif t==6 then
   draw_char(e.anim,e.frame,e.x-portal_cw\2-cam_x,e.y-portal_ch-cam_y,nil,nil,e.active and ptl_rm)
  elseif t==7 then
   draw_char(e.anim,e.frame,e.x-cam_x,e.y-cam_y)
  elseif t~=8 then
   local sx,sy=e.tx*16-cam_x,e.ty*16-cam_y
   if t==1 then sx-=16 end
   draw_char(e.anim,e.frame,sx,sy)
  end
 end
end

function draw_sprojs()
 for p in all(sprojs) do
  local px,py=flr(p.x)-cam_x,flr(p.y)-cam_y
  if p.exp then
   local r=p.et*2
   circ(px,py,r,7)
   if r>3 then circ(px,py,r-3,10) end
   if r>6 then circfill(px,py,r-6,9) end
  else
   circfill(px,py,2,10)
   circfill(px,py,1,7)
  end
 end
end

function _update60()
 -- fade update
 if fade_d~=0 then
  fade_t+=1
  if fade_t>=4 then
   fade_t=0
   fade_v+=fade_d
   if fade_v>=8 then
    fade_v=8
    if gs==2 then reset_game() end gs=gs%2+1
    fade_d=-1
   elseif fade_v<=0 then
    fade_v,fade_d=0,0
   end
  end
 end
 if gs~=1 then
  if fade_d==0 and (btnp(4) or btnp(5)) then sfx(sfx_confirm) fade_d=1 end
  return
 end
 if plr_inv>0 then plr_inv-=1 end
 local lr=plr_inv>30 and 0 or btn(1) and 1 or btn(0) and -1 or 0

 -- -- input buffering --
 if btnp(2) then buf_jump=8 end
 if btnp(4) then buf_atk=8 end
 if btnp(5) then buf_sweep=8 end
 buf_jump=max(0,buf_jump-1)
 buf_atk=max(0,buf_atk-1)
 buf_sweep=max(0,buf_sweep-1)

 -- -- death --
 if state=="death" then
  tick_anim()
  death_t+=1
  if death_t>90 then fade_d=1 end
  update_ents()
  update_sprojs()
  update_parts()
  update_camera()
  return
 end

 -- -- state machine --
 local s=state
 local ba=buf_atk>0 or buf_sweep>0
 if lr~=0 and anim_done(10) and (s=="land" or (not combo_queued and (s=="attack" or (s=="sweep" and not air_atk)))) then
  if s~="land" then end_attack() end
  combo_idx=0 vx,facing=lr*1.5,lr set_anim(a_run,"run")
 elseif s=="idle" or s=="run" then
  -- walked off ledge (wait 4 frames)
  if not grounded and air_time>4 then
   set_anim(a_fall)
   state="fall"
  -- buffered jump
  elseif buf_jump>0 then
   do_jump()
  -- buffered z: start combo
  elseif buf_atk>0 then
   start_combo()
  -- buffered x: sweep
  elseif buf_sweep>0 then
   start_sweep()
  elseif lr~=0 then
   vx,facing=lr*1.5,lr
   if s~="run" then
    set_anim(a_run,"run")
   end
  else
   damp()
   if s~="idle" then
    set_anim(a_idle,"idle")
   end
  end

 elseif s=="jump" then
  air_control(lr)
  if ba then
   start_air_atk()
  elseif vy>=0 then
   set_anim(a_fall,"fall")
  end

 elseif s=="fall" then
  air_control(lr)
  if ba then
   start_air_atk()
  elseif grounded then
   -- check buffers before landing
   if buf_jump>0 then
    do_jump()
   else
    vx=0
    set_anim(a_land,"land")
   end
  end

 elseif s=="land" then
  vx=0
  if anim_done() then
   -- check buffered actions
   if buf_atk>0 then
    start_combo()
   elseif buf_sweep>0 then
    start_sweep()
   else
    set_anim(a_idle,"idle")
   end
  end

 elseif s=="attack" then
  apply_atk_drift()
  -- buffer combo input anytime
  if buf_atk>0
   and combo_idx<#combo_chain then
   combo_queued=true
   buf_atk=0
  end
  if anim_done() then
   end_attack()
   if combo_queued
    and combo_idx<#combo_chain then
    combo_idx+=1
    combo_queued=false
    set_anim(combo_chain[combo_idx])
    sa(combo_chain[combo_idx])
   else
    combo_idx=0
    set_anim(a_idle,"idle")
   end
  end

 elseif s=="sweep" then
  if air_atk then
   air_control(lr)
   if ba and anim_done() then
    start_air_atk()
    return
   elseif grounded then
    air_atk=false
    set_anim(a_land,"land")
   elseif anim_done() then
    air_atk=false
    set_anim(a_fall,"fall")
   end
  else
   apply_atk_drift()
   if anim_done() then
    end_attack()
    if ba then
     vx=0
     set_anim(a_xslice,"attack")
     sa(a_xslice)
     buf_atk,buf_sweep=0,0
     combo_idx=0
    else
     set_anim(a_idle,"idle")
    end
   end
  end

 end

 if grounded and (s=="idle" or s=="run") then safe_x,safe_y=px,py end
 -- -- physics --
 prev_by1=py+19
 if not grounded then
  vy=min(vy+0.15,3)
  air_time+=1
 else
  air_time=0
 end

 -- move X with wall collision
 try_move_x(vx)

 -- move Y, then resolve Y collisions
 py+=vy
 resolve_y()

 -- fallback: bottom of map
 if py+19>=lvl_h*16 then land_on(lvl_h*16) end

 -- clamp to map bounds
 px=mid(3,px,lvl_w*16-4)

 -- hazard tiles
 if tile_flag(px\16,(py+19)\16)&16>0 then hurt_plr() end

 -- attack hitbox vs destructibles + entities
 if state=="attack" or state=="sweep" then
  check_attacks()
 end

 -- update entities & particles
 update_ents()
 update_sprojs()
 update_parts()

 -- update camera
 update_camera()

 -- tick animation
 tick_anim()
end


function _draw()
 if gs==0 then
  cls(0)
  draw_char(a_title,1,0,0)
  text_box("Aletha",36,20,8)
  tt+=1
  if tt>60 then
   local bc=tt%8<4 and 6 or 0
   text_box("press x",96,112,bc)
  end
 elseif gs==2 then
  cls(0)
  text_box("you died",64,46,8)
  if fade_d==0 then
   local bc=(time()*4)%2<1 and 6 or 0
   text_box("press x",64,82,bc)
  end
 else
  cls(lvl_bg)
  draw_mem_layer(3)
  draw_mem_layer(1)
  draw_main_layer()
  draw_ents()
  draw_sprojs()
  local acw=acache[cur_anim].cw
  local ax=(sp_anc[cur_anim] and sp_anc[cur_anim][cur_frame])
        or (anc[cur_anim] and anc[cur_anim][cur_frame])
        or acw\2
  local flip=facing==-1
  local dx=flip and px-(acw-1-ax) or px-ax
  if plr_inv==0 or plr_inv%4<2 then
   draw_char(cur_anim,cur_frame,dx-cam_x,py-cam_y,flip)
  end
  for p in all(parts) do
   local qx,qy=p.x-cam_x,p.y-cam_y
   if p.c then tspr(p.c,qx,qy)
   elseif p.cl then pset(qx,qy,p.cl)
   else circfill(qx,qy,2,8) circfill(qx-1,qy-1,1,14) end
  end
  draw_hp()
  print(gems,2,hp_h+4,8)
  if near_ent then
   local c=near_ent.cost
   text_box(c>0 and "\131 "..c or "\131",near_ent.x-cam_x,near_ent.y-20-cam_y,gems>=c and 7 or 8)
  end
  if zt then text_box(_zt[zt],64,108,7) end
 end
 apply_fade(fade_v)
end
